ICTCR/ICTCR/ICTCR/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICTCR.Models;

namespace ICTCR.Controllers
{
    [Authorize(Roles = "Admin, Helpdesk")]
    public class ProjectsController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Projects
        public ActionResult Index()
        {
            return View(db.MyProjectsContext.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = db.MyProjectsContext.Find(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UnitProjectName")] Projects projects)
        {
            if (ModelState.IsValid)
            {
                db.MyProjectsContext.Add(projects);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projects);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = db.MyProjectsContext.Find(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UnitProjectName")] Projects projects)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projects).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projects);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projects projects = db.MyProjectsContext.Find(id);
            if (projects == null)
            {
                return HttpNotFound();
            }
            return View(projects);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Projects projects = db.MyProjectsContext.Find(id);
            db.MyProjectsContext.Remove(projects);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ICTCR/ICTCR/ICTCR/Controllers/SupportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICTCR.Models;
using ICTCR.ViewModels;
using ICTCR.MJLib;
using System.Web.Configuration;

namespace ICTCR.Controllers
{
    public class SupportsController : Controller
    {
        private MyDbContext db = new MyDbContext();


        // GET: Supports
        [Authorize(Roles = "Admin, Helpdesk, Individual, OnlyUpdateMine")]
        public ActionResult Index()
        {

            string PageNumber = WebConfigurationManager.AppSettings["pageNumber30"];
            int pageNum = Convert.ToInt16(PageNumber);
            //----------Get All Projects----//
            var AllProjects = db.MyProjectsContext.ToList();
            //IEnumerable<SelectListItem> items = db.Provinces.Select(c => new SelectListItem { Value = c.ID.ToString(), Text = c.Name });
            List<SelectListItem> MyProjects = new List<SelectListItem>();
            MyProjects.Add(new SelectListItem { Value = "", Text = "-Select-" });
            foreach (var ProItem in AllProjects)
            {
                MyProjects.Add(new SelectListItem { Value = ProItem.Id.ToString(), Text = ProItem.UnitProjectName });
            }
            ViewBag.ProjectOptions = MyProjects;
            //----------Get All Support Team----//
            var AllSupportTeam = db.MySupportTeam.ToList();
            List<SelectListItem> MySupportTeam = new List<SelectListItem>();
            MySupportTeam.Add(new SelectListItem { Value = "", Text = "-Select-" });
            foreach (var supportTeamItem in AllSupportTeam)
            {
                MySupportTeam.Add(new SelectListItem { Value = supportTeamItem.Id.ToString(), Text = supportTeamItem.FullName });
            }
            ViewBag.supportTeam = MySupportTeam;

            //----------Get All Support----//
            var AllStatus = db.MyStatusContext.ToList();
            List<SelectListItem> MyStatus = new List<SelectListItem>();
            MyStatus.Add(new SelectListItem { Value = "", Text = "-Select-" });
            foreach (var STItem in AllStatus)
            {
                MyStatus.Add(new SelectListItem { Value = STItem.Id.ToString(), Text = STItem.StatusName });
            }
            ViewBag.Sstatus = MyStatus;
            //=============Details==========================//
            int starting = 0;
            if (Request.Form["starting"] != null)
            {
                starting = Convert.ToInt32(Request.Form["starting"]);
            }
            //--------------details-------------------------//
            string strpost = "&ajax=1";
            var S_Total = from s in db.MySupportContext
                          join st in db.MySupportTypeContext on s.SupportTypeId equals st.Id
                          join p in db.MyProjectsContext on s.UnitProjectId equals p.Id
                          join i in db.MySupportTeam on s.ResponsibleId equals i.Id

                          select new SupportsVM
                          {
                              Id = s.Id,
                              RequesterFullName = s.RequesterFullName,
                              RequesterEmail = s.RequesterEmail,
                              UnitProjectName = p.UnitProjectName,
                              SupportTypeName = st.SupportName,
                              SupportTypeCost = st.CostPerSupport,
                              SupportCost = s.SupportCost,
                              ResponsibleFullName = i.FullName,
                              TotalNumberOfSupport = s.TotalNumberOfSupport,
                              StatusId = s.StatusId,
                              DueTimeToComplete = s.DueTimeToComplete


                          };
            int NumRows = S_Total.Count();

            var MyVM = (from s in db.MySupportContext
                        join st in db.MySupportTypeContext on s.SupportTypeId equals st.Id
                        join p in db.MyProjectsContext on s.UnitProjectId equals p.Id
                        join i in db.MySupportTeam on s.ResponsibleId equals i.Id

                        select new SupportsVM
                        {
                            Id = s.Id,
                            RequesterFullName = s.RequesterFullName,
                            RequesterEmail = s.RequesterEmail,
                            UnitProjectName = p.UnitProjectName,
                            SupportTypeName = st.SupportName,
                            SupportTypeCost = st.CostPerSupport,
                            SupportCost = s.SupportCost,
                            ResponsibleFullName = i.FullName,
                            TotalNumberOfSupport = s.TotalNumberOfSupport,
                            CreatedDate = s.CreatedDate,
                            TimeToAction = st.TimeToAction,
                            CostPerMinute = i.PerMinuteCost,
                            MinutesWorked = s.MinutesWorked,
                            ActualCost = s.ActualCost,
                            StatusId = s.StatusId,
                            DueTimeToComplete = s.DueTimeToComplete

                        }).AsEnumerable().OrderByDescending(o => o.Id).Skip(starting).Take(pageNum);



            string links = Pagination.paginate(NumRows, starting, pageNum, "", "page", strpost);

            ViewBag.link = links;
            if (Request.IsAjaxRequest())
            {
                return PartialView("Index2", MyVM);
            }
            return View(MyVM);
        }

        [Authorize(Roles = "Admin, Helpdesk, Individual, OnlyUpdateMine")]
        public ActionResult MyTickets()
        {
            string PageNumber = WebConfigurationManager.AppSettings["pageNumber30"];
            int pageNum = Convert.ToInt16(PageNumber);
            //----------Get All Projects----//
            var AllProjects = db.MyProjectsContext.ToList();
            //IEnumerable<SelectListItem> items = db.Provinces.Select(c => new SelectListItem { Value = c.ID.ToString(), Text = c.Name });
            List<SelectListItem> MyProjects = new List<SelectListItem>();
            MyProjects.Add(new SelectListItem { Value = "", Text = "-Select-" });
            foreach (var ProItem in AllProjects)
            {
                MyProjects.Add(new SelectListItem { Value = ProItem.Id.ToString(), Text = ProItem.UnitProjectName });
            }
            ViewBag.ProjectOptions = MyProjects;
            //----------Get All Support Team----//
            var AllSupportTeam = db.MySupportTeam.ToList();
            List<SelectListItem> MySupportTeam = new List<SelectListItem>();
            MySupportTeam.Add(new SelectListItem { Value = "", Text = "-Select-" });
            foreach (var supportTeamItem in AllSupportTeam)
            {
                MySupportTeam.Add(new SelectListItem { Value = supportTeamItem.Id.ToString(), Text = supportTeamItem.FullName });
            }
            ViewBag.supportTeam = MySupportTeam;

            //----------Get All Support----//
            var AllStatus = db.MyStatusContext.ToList();
            List<SelectListItem> MyStatus = new List<SelectListItem>();
            MyStatus.Add(new SelectListItem { Value = "", Text = "-Select-" });
            foreach (var STItem in AllStatus)
            {
                MyStatus.Add(new SelectListItem { Value = STItem.Id.ToString(), Text = STItem.StatusName });
            }
            ViewBag.Sstatus = MyStatus;
            //=============Details==========================//
            int starting = 0;
            if (Request.Form["starting"] != null)
            {
                starting = Convert.ToInt32(Request.Form["starting"]);
            }
            //--------------details-------------------------//
            string strpost = "&ajax=1";

            var UserName = User.Identity.Name;
            var TrimedUser = UserName.TrimStart("UNDPAF\\".ToCharArray());
            //var ReplaceTheDotWithSpace = TrimedUser.Replace(@".", " ");
            var TheUser = db.MySupportTeam.FirstOrDefault(u => u.UserName.Equals(TrimedUser, StringComparison.CurrentCultureIgnoreCase));

            var S_Total = from s in db.MySupportContext
                          where s.ResponsibleId == TheUser.Id
                          join st in db.MySupportTypeContext on s.SupportTypeId equals st.Id
                          join p in db.MyProjectsContext on s.UnitProjectId equals p.Id
                          join i in db.MySupportTeam on s.ResponsibleId equals i.Id

                          select new SupportsVM
                          {
                              Id = s.Id,
                              RequesterFullName = s.RequesterFullName,
                              RequesterEmail = s.RequesterEmail,
                              UnitProjectName = p.UnitProjectName,
                              SupportTypeName = st.SupportName,
                              SupportTypeCost = st.CostPerSupport,
                              SupportCost = s.SupportCost,
                              ResponsibleFullName = i.FullName,
                              TotalNumberOfSupport = s.TotalNumberOfSupport,
                              StatusId = s.StatusId,
                              DueTimeToComplete = s.DueTimeToComplete


                          };
            int NumRows = S_Total.Count();

            var MyVM = (from s in db.MySupportContext
                        where s.ResponsibleId == TheUser.Id
                        join st in db.MySupportTypeContext on s.SupportTypeId equals st.Id
                        join p in db.MyProjectsContext on s.UnitProjectId equals p.Id
                        join i in db.MySupportTeam on s.ResponsibleId equals i.Id

                        select new SupportsVM
                        {
                            Id = s.Id,

ICTCR/ICTCR/ICTCR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UNDP Afghanistan Online ICT Ticketing System</title>
    <!-- Bootstrap -->
    <link href="~/Scripts/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Scripts/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/Scripts/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="~/Content/tp/css/custom.css" rel="stylesheet">
    <script type="text/javascript" src="~/Content/JUI/jquery.js"></script>
    <script>
        function MJPaging(page, divname, starting, str) {
            var ajax_image = "<img src='../Content/loading.GIF' >";
            $('#' + divname).html(ajax_image);
            var params = '&starting=' + starting + '&' + str;
            $.ajax({
                url: page,
                type: "POST",
                data: params,

            })
            .done(function (r) {

                $('#' + divname).html(r);
            });
        }
    </script>
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="#" class="site_title"><i class="fa fa-phone"></i> <span>ICT Call (9999)</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    <!--<div class="profile">
                        <div class="profile_pic">
                            <img src="images/img.jpg" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>John Doe</h2>
                        </div>
                    </div>-->
                    <!-- /menu profile quick info -->
                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section4">
                            <h3>@Html.ActionLink("Dashboard", "MinutesWorked", "Dashboard",null,new { @class="btn btn-info", @style="margin-left:18%;"})</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-home"></i> ICT Help Desk <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>
                                            @Html.ActionLink("Units/Projects", "Index", "Projects")
                                        </li>
                                        <li>
                                            @Html.ActionLink("Status", "Index", "Status")
                                        </li>
                                        <li>
                                            @Html.ActionLink("Support Type", "Index", "SupportTypes")
                                        </li>
                                        <li>
                                            @Html.ActionLink("Support Team", "Index", "SupportTeams")
                                        </li>
                                        <li>
                                            @Html.ActionLink("Create a Ticket", "Create", "Supports")
                                        </li>
                                        <li>

                                            @Html.ActionLink("Ticket List", "Index", "Supports")
                                        </li>
                                   

                                    </ul>
                                </li>


                            </ul>
                        </div>


                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <!--<div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>-->
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav class="" role="navigation">
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>

                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li style="float:left">
                                <a href="#">UNDP Afghanistan Online ICT Ticketing System</a>
                            </li>


                            <li class="">
                                <a href="#">
                                    <!--<img src="images/img.jpg" alt="">-->@User.Identity.Name
                                    <span class=" fa fa-angle-down"></span>
                                </a>

                            </li>

                        </ul>
                    </nav>
                </div>
            </div>

            <!-- /top navigation -->
            <!-- Page Content-->
            @RenderBody()
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Designed and Developed By:<a href="#" class="colorpicker-hue">UNDP Afghanistan ICT</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>
    <!-- jQuery -->
    <!--<script src="~/Scripts/vendors/jquery/dist/jquery.min.js"></script>-->
  
    <!-- Bootstrap -->
    <script src="~/Scripts/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/Scripts/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/Scripts/vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="~/Scripts/vendors/iCheck/icheck.min.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="~/Content/tp/js/custom.js"></script>
</body>
</html>