ICTCR/ICTCR/ICTCR/Controllers/SupportTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICTCR.Models;
using ICTCR.ViewModels;

namespace ICTCR.Controllers
{
   
    public class SupportTypesController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: SupportTypes

        public ActionResult Index()
        {
            var StypeQuery = from s in db.MySupportTypeContext
                             join t in db.DateTimeSpans on s.DateTimeSpanId equals t.Id
                             select new SupportTypeVM
                             {
                                 Id = s.Id,
                                 SupportName = s.SupportName,
                                 CostPerSupport = s.CostPerSupport,
                                 Minutes = s.Minutes,
                                 TimeToAction = s.TimeToAction,
                                 DateTimeName = t.DateTimeName
                             };
            return View(StypeQuery);
        }

        // GET: SupportTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupportType supportType = db.MySupportTypeContext.Find(id);
            if (supportType == null)
            {
                return HttpNotFound();
            }
            return View(supportType);
        }
        [Authorize(Roles = "Admin, Helpdesk")]
        // GET: SupportTypes/Create
        public ActionResult Create()
        {
            //----------Get All Time Span----//
            var AllTimeSpan = db.DateTimeSpans.ToList();
            List<SelectListItem> MyTimeSpan = new List<SelectListItem>();
            MyTimeSpan.Add(new SelectListItem { Value = "", Text = "-Select-" });
            foreach (var STItem in AllTimeSpan)
            {
                MyTimeSpan.Add(new SelectListItem { Value = STItem.Id.ToString(), Text = STItem.DateTimeName });
            }
            ViewBag.TimeSpanOption = MyTimeSpan;
            return View();
        }

        // POST: SupportTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SupportName,CostPerSupport,Minutes,TimeToAction,DateTimeSpanId,Description")] SupportType supportType, int TimeSpanOption)
        {
            if (ModelState.IsValid)
            {
                supportType.DateTimeSpanId = TimeSpanOption;
                db.MySupportTypeContext.Add(supportType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(supportType);
        }
        [Authorize(Roles = "Admin, Helpdesk")]
        // GET: SupportTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupportType supportType = db.MySupportTypeContext.Find(id);
            if (supportType == null)
            {
                return HttpNotFound();
            }

            //----------Get All Time----//
            var AllTimeSpan = db.DateTimeSpans.ToList();

            List<SelectListItem> MyTimeSpan = new List<SelectListItem>();
     
            foreach (var STItem in AllTimeSpan)
            {
                var item = new SelectListItem();
                if (STItem.Id == supportType.DateTimeSpanId)
                {
                    item.Selected = true;
                }
                item.Value = STItem.Id.ToString();
                item.Text = STItem.DateTimeName;

                MyTimeSpan.Add(item);
            }
            ViewBag.TimeSpanOption = MyTimeSpan;
            return View(supportType);
        }

        // POST: SupportTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SupportName,CostPerSupport,Minutes,TimeToAction,DateTimeSpanId,Description")] SupportType supportType, int TimeSpanOption)
        {
            if (ModelState.IsValid)
            {
                supportType.DateTimeSpanId = TimeSpanOption;
                db.Entry(supportType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supportType);
        }

        // GET: SupportTypes/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupportType supportType = db.MySupportTypeContext.Find(id);
            if (supportType == null)
            {
                return HttpNotFound();
            }
            return View(supportType);
        }

        // POST: SupportTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SupportType supportType = db.MySupportTypeContext.Find(id);
            db.MySupportTypeContext.Remove(supportType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ICTCR/ICTCR/ICTCR/Views/SupportTypes/Create.cshtml
@model ICTCR.Models.SupportType

@{
    ViewBag.Title = "Create";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-8 col-xs-8">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Add New Item <small>* Means Required</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>SupportType</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.SupportName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupportName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SupportName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CostPerSupport, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CostPerSupport, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CostPerSupport, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Minutes, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Minutes, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Minutes, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.TimeToAction, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.TimeToAction, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.TimeToAction, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Unit/Project:</label>
                                    <div class="col-md-10">
                                        @Html.DropDownList("TimeSpanOption", null, htmlAttributes: new { @class = "form-control has-feedback-left", @required = "required" })
                                        <span class="fa fa-star form-control-feedback left" aria-hidden="true"></span>

                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>

ICTCR/ICTCR/ICTCR/Views/SupportTypes/Delete.cshtml
@model ICTCR.Models.SupportType

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SupportType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SupportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SupportName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostPerSupport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostPerSupport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Minutes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Minutes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ICTCR/ICTCR/ICTCR/Views/SupportTypes/Details.cshtml
@model ICTCR.Models.SupportType

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SupportType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SupportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SupportName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostPerSupport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostPerSupport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Minutes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Minutes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeToAction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeToAction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ICTCR/ICTCR/ICTCR/Views/SupportTypes/Edit.cshtml
@model ICTCR.Models.SupportType

@{
    ViewBag.Title = "Edit";
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-8 col-xs-8">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Add New Item <small>* Means Required</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>SupportType</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.SupportName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SupportName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SupportName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CostPerSupport, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CostPerSupport, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CostPerSupport, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Minutes, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Minutes, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Minutes, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.TimeToAction, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.TimeToAction, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.TimeToAction, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-2">Unit/Project:</label>
                                    <div class="col-md-10">
                                        @Html.DropDownList("TimeSpanOption", null, htmlAttributes: new { @class = "form-control has-feedback-left", @required = "required" })
                                        <span class="fa fa-star form-control-feedback left" aria-hidden="true"></span>

                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>

ICTCR/ICTCR/ICTCR/Views/SupportTypes/Index.cshtml
@model IEnumerable<ICTCR.ViewModels.SupportTypeVM>

@{
    ViewBag.Title = "Index";
}
<div id="page">
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="clearfix"></div>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">

                    @Html.ActionLink("Add New Item", "Create", "SupportTypes", null, new { @class = "btn btn-danger" })

                    <a class="btn btn-success" style="float:right!important">Generate Report</a>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <!--<p>
                       <a href="#" class="btn btn-primary">Book a Car</a>
                    </p>-->
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.SupportName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CostPerSupport)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Minutes)
                                </th>
                                <th>
                                    Time to Action
                                </th>

                                <th></th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SupportName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CostPerSupport)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Minutes)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TimeToAction) - @Html.DisplayFor(modelItem => item.DateTimeName)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>